@host=https://localhost:7117
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYjAxODUwNC0xOGNlLTQzOTctYTJkNi1iMzM2NGEyNTA3NWIiLCJnaXZlbl9uYW1lIjoiRlciLCJmYW1pbHlfbmFtZSI6IndpbG1zIiwianRpIjoiYzIwMjMyNTAtYzJkMS00MWQ1LTg4NzItZjFiNmUxYzYzYzQ4IiwiZXhwIjoxNjY5NTc5NTg1LCJpc3MiOiJGaW5lRGlubmVyIiwiYXVkIjoiRmluZURpbm5lciJ9.miESQNtNaYKrC2E8WykZ2-JHgTqN2B74ssjiDnh5zH4eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZWY0ZWE1NC0yN2YzLTQzMWEtYWYxMS1mYzZhMzIwZjliYWUiLCJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiJlNjNmODEyMC1lOTkwLTRiMzAtOGE3OS01ZjdiN2I0YWE4ZjkiLCJleHAiOjE2Njk1Nzk0MzEsImlzcyI6IkZpbmVEaW5uZXIiLCJhdWQiOiJGaW5lRGlubmVyIn0.hCxFlFZZ_zinI8SAoaRR4bgpsBI6pPbLDQQOUGXbWPE

GET {{host}}/Dinners
Content-Type: : application/json
Authorization: Bearer {{token}}

{

}